<?php

class SE_missatsamtal_HE extends superfecta_base {

    public $description = "http://missatsamtal.se - A datasource identifying telemarketers in Sweden.";
    public $version_requirement = "2.11";

    public $source_param = array(
             'SPAM_Value' => array (
               'description' => 'Specify the number of listings required to mark a call as spam.',
               'type' => 'number',
	       'default' => 3
             ),
             'API_Key' => ARRAY (
               'description' => 'API Key is required for missatsamtal.se (look at https://missatsamtal.se/api for more information)',
               'type' => 'text'
             )
    );

    function get_caller_id($thenumber, $run_param=array()) {
        $caller_id = null;

        $this->DebugPrint("Searching missatsamtal.se... ");
        $url = "https://api.missatsamtal.se/?action=search&number=$thenumber&numberOfCompanies=1&key=".$run_param['API_Key'];
        $value = $this->get_url_contents($url);

	// $VALUE = NAMNET PA FORETAGET
	// $spamcalls = antalet ganger som spamnumret ar listat
	
	$start = strpos($value, "comments");            // STARTPOS is position for the first char in "comments"
        $value = substr($value,$start+11);              // Skip text "comments"
		
		if (strpos($value, "error") == false){
			$this->DebugPrint("NEWVAULE=".$value."\n\n");} else {
				$start = strpos($value, "error");				// STARTPOS is position for the first char in "error"
				$value = substr($value,$start+23);				// Skip text "error" and "missatsamtal.se"
				
				$end = strpos($value, "\"");					// Look for next ["] indication the end of the error msg
				$error = substr($value,0,$end);					// Save result in $error from startpost 0 to endpos $end
				$this->DebugPrint("\n\n<b>Sorry " . $error . "!!!!</b>");
			}
        $end = strpos($value, "\"");                    // Look for next ["] indication the end of the number
        $spamcalls = substr($value,0,$end);             // Save result in $spamcalls
	
	$start = strpos($value, "name");
        $value = substr($value,$start+7);               // Skip text "name"

        $end = strpos($value, "\"");                    // Look for next ["] indication the end of the name
        $value = substr($value,0,$end);                 // Save result in $value from startpost 0 to endpos $end
		
	$SPAM_threshold = intval($spamcalls);
        $this->DebugPrint("SPAMVALUE RECEIVED=".$SPAM_threshold."\n");
	    
        if ($value != "0" && empty($error)) {
            $this->spam = true;
            $this->DebugPrint(" determined to be SPAM");
        } else {
			if (isset($error)) {
				$this->DebugPrint("Read bold text above fatal error!!!");
			} else {
				$this->DebugPrint("Not a SPAM caller");
			}
	    return("");
        }
        return($value);
    }
}
